### ISSUE TITLE
Royal street flush vs street flush evaluated incorrectly

### ISSUE THREAD

**Issue by snarb** [zekyll/OMPEval#9]
Board:  KsQsJsTs9d
First hand:  AsAh. Strength:   36866
Second: Ac9s. Strength:   36867

First-hand makes street flush so it rank should higher.

**Comment by anatoly-os** [comment]
Well, second hand is also a street flush, but, indeed first hand is a winner.

**Comment by snarb** [comment]
First one is royal flush. I have corrected title. Thanks.
